Chmelar_Bielik_Honzatko_Hubicka/Pages/ActiveGames.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Chmelar_Bielik_Honzatko_Hubicka.Models;
using Chmelar_Bielik_Honzatko_Hubicka.Services;
using Chmelar_Bielik_Honzatko_Hubicka.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace Chmelar_Bielik_Honzatko_Hubicka.Pages
{
    [Authorize]
    public class ActiveGamesModel : PageModel
    {
        [TempData]
        public string MessageSuccess { get; set; }
        [TempData]
        public string MessageError { get; set; }


        readonly GameManipulator _gameManipulator;
        public ActiveGamesModel(GameManipulator gameManipulator, GameSessionStorage<Guid> gss)
        {
            _gameManipulator = gameManipulator;
            MyGameLists = new List<Game>();
            JoinGameLists = new List<Game>();
            _gss = gss;
        }
        readonly GameSessionStorage<Guid> _gss;
        public List<Game> MyGames { get; set; }
        public List<Game> OtherGames { get; set; }
        public string UserId { get; set; }
        public List<Game> MyGameLists { get; set; }
        public List<Game> JoinGameLists { get; set; }
        public void OnGet()
        {
            MyGames = new List<Game>();
            MyGames = _gameManipulator.MyGamesList();
            OtherGames = new List<Game>();
            OtherGames = _gameManipulator.JoinGamesList();
            UserId = _gss.GetUserId();
        }
         public IActionResult OnGetGame(Guid id)
         {
            return RedirectToPage("./Gameon");
         }
        public IActionResult OnGetRemoveGame(Guid id)
        {
            bool result = _gameManipulator.RemoveGame(id);
            if (result)
            {
                MessageSuccess = "Game was removed.";
            }

            else
            {
                MessageError = "Game was unable to be removed.";
            }
            return RedirectToPage("./ActiveGames");
        }

        public IActionResult OnGetJoinGame(Guid id)
        {
            _gameManipulator.JoinGame(id);
            return RedirectToPage("./Gameon");
        }

    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Chmelar_Bielik_Honzatko_Hubicka.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Gameon.cshtml.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Chmelar_Bielik_Honzatko_Hubicka.Helpers;
using Chmelar_Bielik_Honzatko_Hubicka.Models;
using Chmelar_Bielik_Honzatko_Hubicka.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chmelar_Bielik_Honzatko_Hubicka
{
    public class GameonModel : PageModel
    {
        readonly GameManipulator _gl;
        
        public string Color { get; set; } //Color of the cell.
        public List<NavyBattlePiece> Pieces { get; set; }
        public GameDeskModel GameDesk = new GameDeskModel();
        public string Text { get; set; }
        public string PlayerId { get; set; }

        public GameonModel(GameManipulator gl)
        {
            Color = "unknown";
            _gl = gl;
            PlayerId = _gl.activeUserId;
        }

        public void OnGet()
        {

            Pieces = _gl.GetBattlefield();
        }

        public void OnGetHit(int pieceId)
        {
            _gl.Hit(pieceId);
            foreach (var p in Pieces)
            {
                if (p.State == BattlePieceState.Hitted_Ship)
                {
                    Color = "hittedship";
                    Text = "You hitted a ship.";
                }

                else if (p.State == BattlePieceState.Hitted_Water)
                {
                    Color = "hittedwater";
                    Text = "You hitted a water.";
                }

                else
                {
                    Color = "unknown";
                }
            }

            GameDesk.Pieces = Pieces;
        }

        public void OnPost(string text)
        {
            text = Text;

            TempData.AddMessage("messagebox", TempDataExtension.MessageType.success, text);
        }
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Chmelar_Bielik_Honzatko_Hubicka.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Preparation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Chmelar_Bielik_Honzatko_Hubicka.Helpers;
using Chmelar_Bielik_Honzatko_Hubicka.Models;
using Chmelar_Bielik_Honzatko_Hubicka.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chmelar_Bielik_Honzatko_Hubicka
{
    public class PreparationModel : PageModel
    {
        readonly GameManipulator _gm;
        public string Text { get; set; }

        public PreparationModel(GameManipulator gm)
        {
            _gm = gm;
        }

        public void OnPostMessage()
        {
            TempData.AddMessage("messagebox", TempDataExtension.MessageType.success, Text);
        }
        public void OnGet()
        {

        }

        public IActionResult OnGetGame()
        {
            _gm.StartGame();

            return RedirectToPage("./Gameon");
        }
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Chmelar_Bielik_Honzatko_Hubicka.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/ActiveGames.cshtml
@page
@model Chmelar_Bielik_Honzatko_Hubicka.Pages.ActiveGamesModel
@{
    ViewData["Title"] = "ActiveGames";
}

@if (Model.MessageSuccess?.Length > 0)
{
    <div class="alert alert-success" role="alert">@TempData["MessageSuccess"]<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
}
@if (Model.MessageError?.Length > 0)
{
    <div class="alert alert-warning" role="alert">@TempData["MessageError"]<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
}
<a asp-page="/Preparation" class="btn btn-success text-right">Create a new game</a>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            <h1>Join Game!</h1>
            <h2> My Games</h2>
            <div class="table-responsive-sm">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Game State</th>
                            <th>Player 1</th>
                            <th>Player 2</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.MyGames)
                        {
                        <tr>
                            <td>@item.Gamestate</td>
                            <td>@item.Owner.UserName</td>
                            @if (item.Player != null)
                            {
                                <td>@item.Player.UserName</td>
                            }
                            else
                            {
                                <td></td>
                            }
                            <th></th>
                        </tr>
                        <td>
                            <a class="btn btn-primary" asp-page-handler="Game" asp-route-id="@item.GameId">Play</a>
                        </td>
                        @if (Model.UserId == item.OwnerId)
                        {
                            <td>
                                <a class="btn btn-danger" asp-page-handler="RemoveGame" asp-route-id="@item.GameId">Delete</a>
                            </td>

                        }
                        }
                    </tbody>
                </table>

                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Game State</th>
                                <th>Owner</th>
                                <th>Current player</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model.OtherGames)
                            {
                            <tr>
                                <td>@item.Gamestate</td>
                                <td>@item.Owner.UserName</td>
                                @if (item.Player != null)
                                {
                                    <td>@item.Player.UserName</td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                <td>
                                    <a class="btn btn-primary" asp-page-handler="JoinGame" asp-route-id="@item.GameId">Join</a>
                                </td>
                            </tr>
                            }
                        </tbody>


                    </table>
                </div>
        </main>
    </div>
</body>

Chmelar_Bielik_Honzatko_Hubicka/Pages/Gameon.cshtml
@page
@model Chmelar_Bielik_Honzatko_Hubicka.GameonModel
@{
    ViewData["Title"] = "Gameon";
}

<h1>Gameon</h1>


<h3>Game has started!</h3>

@if (Model.PlayerId != null)
{
    string key = "messagebox";
    <partial name="_GameMessages" model="key" />

    <partial name="_GameDesk" model="@Model.GameDesk" />
}

<a class="btn btn-success" href="./Gameon">Reload Page</a>

Chmelar_Bielik_Honzatko_Hubicka/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using Chmelar_Bielik_Honzatko_Hubicka.Models
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<body>
    <div class="container">
        <h1 class="display-4">Welcome to game Battleships!</h1>
        @if (SignInManager.IsSignedIn(User))
        {
            <a class="btn btn-info" href="./Preparation">Create a new game</a>
            <a class="btn btn-info" href="./ActiveGames">Join Game</a>
        }
        else
        {
            <a class="btn btn-info" href="../Identity/Account/Login">Log in</a>
            <a class="btn btn-info" href="../Identity/Account/Register">Register</a>
        }
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BattleShips v0.6 - <a href="/Privacy">Privacy</a>
        </div>
    </footer>
</body>

Chmelar_Bielik_Honzatko_Hubicka/Pages/Preparation.cshtml
@page
@model Chmelar_Bielik_Honzatko_Hubicka.PreparationModel
@{
    ViewData["Title"] = "Preparation";
}

<h1>Preparation</h1>

<a class="btn btn-primary" asp-page-handler="Game">New Game</a>
<a class="btn btn-primary" href="./ActiveGames">To active game</a>