Chmelar_Bielik_Honzatko_Hubicka/Pages/Gameon.cshtml.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Chmelar_Bielik_Honzatko_Hubicka.Helpers;
using Chmelar_Bielik_Honzatko_Hubicka.Models;
using Chmelar_Bielik_Honzatko_Hubicka.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Chmelar_Bielik_Honzatko_Hubicka
{
    public class GameonModel : PageModel
    {
        readonly GameManipulator _gl;
        
        public string Color { get; set; } //Color of the cell.
        public List<NavyBattlePiece> Pieces { get; set; }
        public GameDeskModel GameDesk = new GameDeskModel();
        public string Text { get; set; }
        public string PlayerId { get; set; }

        public GameonModel(GameManipulator gl)
        {
            Color = "unknown";
            _gl = gl;
            PlayerId = _gl.activeUserId;
        }

        public void OnGet()
        {

            Pieces = _gl.GetBattlefield();
        }

        public void OnGetHit(int pieceId)
        {
            _gl.Hit(pieceId);
            foreach (var p in Pieces)
            {
                if (p.State == BattlePieceState.Hitted_Ship)
                {
                    Color = "hittedship";
                    Text = "You hitted a ship.";
                }

                else if (p.State == BattlePieceState.Hitted_Water)
                {
                    Color = "hittedwater";
                    Text = "You hitted a water.";
                }

                else
                {
                    Color = "unknown";
                }
            }

            GameDesk.Pieces = Pieces;
        }

        public void OnPost(string text)
        {
            text = Text;

            TempData.AddMessage("messagebox", TempDataExtension.MessageType.success, text);
        }
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Shared/_GameDesk.cshtml
@model GameDeskModel
@using Chmelar_Bielik_Honzatko_Hubicka.Models

@{
    List<NavyBattlePiece> pieces = Model.Pieces;
    string color = Model.Color;
}

<div class="Desk">
    <table class="table">
        <tbody>
            @foreach (var row in pieces.GroupBy(p => p.PosY))
            {
                <tr>
                    @foreach (var piece in row)
                    {
                        <td class="game-piece-@piece.State">
                            <a class="btn btn-outline-light" asp-page-handler="Hit" asp-route-pieceid="@piece.Id">[@piece.PosX, @piece.PosY]</a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

Chmelar_Bielik_Honzatko_Hubicka/Pages/Shared/_GameMessages.cshtml
@model string
@using Chmelar_Bielik_Honzatko_Hubicka.Helpers

@{
    List<TempDataExtension.MessageData> messages = TempData.GetMessages(Model);
}

@if (messages != default)
{
    @foreach (var message in messages)
    {
        <div class="alert alert-@message.MessageType alert-dismissible fade show" role="alert">
            <strong>Info:</strong> @message.MessageText
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

Chmelar_Bielik_Honzatko_Hubicka/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Chmelar_Bielik_Honzatko_Hubicka.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chmelar_Bielik_Honzatko_Hubicka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
@if (SignInManager.IsSignedIn(User))
{
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand">BattleShips</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@UserManager.GetUserName(User)</a>
                    </li>
                    <li class="nav-item">
                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/Index", new { area = "" })">
                            <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                        </form>
                    </li>
                </ul>

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="./ActiveGames">Seznam her</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
}
else
{
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand">BattleShips</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <a class="nav-link text-dark" href="../identity/account/register">Register</a>
                    <a class="nav-link text-dark" href="../identity/account/login">Log in</a>
            </div>
        </div>
    </nav>
}

<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>